# fly.toml app configuration file generated for boletika-api on 2023-06-20T22:29:35-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "boletika-api"
primary_region = "qro"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
